### ISSUE TITLE
Implicit declaration of function 'sqlfs_xxx_yyyy' is invalid in C99

### ISSUE THREAD

**Issue by Aanabidden** [ChatSecure/IOCipher-ObjC#5]
I m trying to run the exapmle on Xcode 7,8 on iOS 9,10 device but i m getting error saying “Implicit declaration of function 'sqlfs_xxx_yyyy' is invalid in C99” for below mentioned methods:
sqlfs_open_password
sqlfs_open_key
sqlfs_change_password
sqlfs_rekey

i guess it is all hapening because of libsqlfs i used https://github.com/guardianproject/libsqlfs release 1.3.2
can you guide me what i am doing wrong or missing that i m getting this error.

**Comment by ShebinKoshy132** [comment]
add -DHAVE_LIBSQLCIPHER in
Target -> Build Settings-> Other C Flags
